### ISSUE TITLE
maybe don‘t work for std cpp standard library

### ISSUE THREAD

**Issue by Yihen** [nickdiego/compiledb#109]
In bitcoin opensource, I use `compilerdb -n make` to generate compile_commands.json; when I open the *.cpp file, ccls report ERROR as following pic:

![WX20201111-174002](https://user-images.githubusercontent.com/7480459/98904462-9e37a880-24f4-11eb-9e3d-36ef1af6a2ae.png)

How to handle it?

**Comment by Yihen** [comment]
have solved by setting coc.vim configuration about clang item.

**Comment by Yihen** [comment]
https://github.com/bitcoin/bitcoin/issues/20369

**Comment by shenliyang521** [comment]
@Yihen compiledb/cli.py中，
def cli(ctx, infile, outfile, build_dir, exclude_files, no_build, verbose, overwrite, no_strict, add_predefined_macros,use_full_path, command_style)，这些参数的出处在哪，我在中文系统下需要调试，好像是no_strict的这个参数对生成的json文件有一影响
