### ISSUE TITLE
Failure on openssl 1.0.1

### ISSUE THREAD

**Issue by zhaogang92** [nickdiego/compiledb#58]
When running it on openssl 1.0.1f, there is an error:

##Processing build commands from <fdopen>
make: *** [Makefile] Error 1
make: Failed to remake makefile 'Makefile'.
##Loaded compilation database with 0 entries from compile_commands.json
##Writing compilation database with 0 entries to compile_commands.json

The command I used:
./config
compiledb -n make

Environment: Ubuntu 16.04.5, compiledb is installed with pip.

**Comment by nickdiego** [comment]
Just tested it by miself. It seems like `openssl` in "incompatible" with dry-run make option (`-n` / `--dry-run`) which is used under the hood to implement `compiledb make -n`. In this cases, I recommend to:

```sh
make | tee build.log && compiledb --parse build.log
```
This worked for me, the output was:

```
WARNING: Token 'COND_ERROR' defined, but not used
WARNING: There is 1 unused token
## Processing build commands from build.log
### Just parsed 669 compile commands.
## Loaded compilation database with 0 entries from compile_commands.json
## Writing compilation database with 621 entries to compile_commands.json
## Done.
```
