### ISSUE TITLE
Please add argument to specify input compile database file

### ISSUE THREAD

**Issue by rzuckerm** [nickdiego/compiledb#59]
[This code](https://github.com/nickdiego/compiledb/blob/master/compiledb/__init__.py#L48) is assuming that the original compilation database file is called `compile_commands.json` and is in the same directory where `compiledb` is executed. Please add a command-line argument to specify the input compilation database file

**Comment by nickdiego** [comment]
Hi,
I've been really busy these days. So feel free to send a PR :-)
thanks

**Comment by rzuckerm** [comment]
@nickdiego Thanks, I'm working on the changes right now.

**Comment by rzuckerm** [comment]
https://github.com/nickdiego/compiledb/pull/61 is ready for review
