### ISSUE TITLE
(idea/suggestion) quiet/silent flag

### ISSUE THREAD

**Issue by Falkgaard** [nickdiego/compiledb#66]
Hi,

It would be nice if there were an argument like "-s" to tell compiledb not to print the lines starting with ## or the line with the ().

At the moment I'm using: 

> `compiledb make | grep -v "## *\|()"`

when compiling from my terminal, but if I run the build in my editor (Sublime Text 3) the grep fucks up the output (instead of getting real-time printing, it won't print anything until it's done with the whole build).

Regards,
-Falk

**Comment by agnjunio** [comment]
I believe I already suggested this feature in #63, it's simple but useful. 

If you're feeling like creating a pull request, feel free to do so. Otherwise, I can implement it in my spare time.

**Comment by nickdiego** [comment]
That would be nice. If possible, we could take the opportunity to get it of `if (verbose) print(..)` in favor of logging APIs.

Marking this as part of the release milestone.

**Comment by nickdiego** [comment]
Closing this as #68 has landed.
