### ISSUE TITLE
add support for a custom make path

### ISSUE THREAD

**Issue by berilevi** [nickdiego/compiledb#70]
Can you please add support for specifying a path to a custom make rather than the one used in system path. This is useful for replacing default make with compiledb so all make commands are automatically redirected to compiledb. 
So forexample in a shell script named "make" I want to be able to do compiledb  -o commands.json -c /usr/bin/mymake $1 $2 ...
Build systems using custom tools like yocto's bitbake for example I am hoping the above suggestion should work to intercept all make commands.
Kind Regards,
Beri

**Comment by agnjunio** [comment]
Have you tried to use the pipe input method?

Example:
``` 
/usr/bin/yourmake | compiledb
```

**Comment by berilevi** [comment]
I cant start a build by running my own make. In yocto you have to use bitbake. As a workaround i wrote a script to collect log files and fed them to compiledb
