### ISSUE TITLE
Next release schedule?

### ISSUE THREAD

**Issue by LarsMichelsen** [nickdiego/compiledb#81]
Hi,

the release of 0.9.8 was in 10/2018. We are waiting for a fix that has already been merged to the master to be included in a released version.

Can someone tell when we can expect the next version?

Thanks!

**Comment by nickdiego** [comment]
Hi.
I've been busy with other stuff these days and forgot to upload 0.10.0 release. I'll do it now.
Thanks for your feedback.

**Comment by nickdiego** [comment]
v0.10.0 is now available.
Appreciate your feedback.

**Comment by martinlightmatter** [comment]
Thanks for the release! I was also needing some features from master.

**Comment by LarsMichelsen** [comment]
awesome! Thank you! :1st_place_medal:
