### ISSUE TITLE
How to run this tool when the Makefile isn't in the current folder

### ISSUE THREAD

**Issue by fbs2016** [nickdiego/compiledb#91]
I want to run the tool with the Makefile under other folders.
I try to run it with option "-d" : compiledb -d subfolder/ make,
but it report err as command "make" can't find the file Makefile.

What happens if I set the option "-d" with a folder? Thanks
-d, --build-dir PATH   Path to be used as initial build dir

**Comment by saimen** [comment]
Make's option to use a Makefile in a specific directiory is `-C` 
I didn't test this but you should be able to call `compiledb make -C subfolder`

**Comment by fbs2016** [comment]
Saimen
Thanks a lot.
