### ISSUE TITLE
Support for .c++ file extension

### ISSUE THREAD

**Issue by tobbelobb** [nickdiego/compiledb#99]
Hello Compiledb developers!

Could we change
```
file_regex = re.compile(r"^.+\.c$|^.+\.cc$|^.+\.cpp$|^.+\.cxx$|^.+\.s$", re.IGNORECASE)
```
into
```
file_regex = re.compile(r"^.+\.c$|^.+\.cc$|^.+\.cpp$|^.+\.cxx$|^.+\.c\+\+$|^.+\.s$", re.IGNORECASE)
```
please please pleeeease?

I know .c++ is not a widely used file extension, but if you ever see it in the wild, you would expect the file to contain c++ source code and nothing else, right?

**Comment by Thaodan** [comment]
PR?

**Comment by tobbelobb** [comment]
Ok, created one: https://github.com/nickdiego/compiledb/pull/108

Closing this issue, we can keep further comments in the PR
